version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      network:
        ipv4_address: 10.5.0.2
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - 61616:61616
      - 8161:8161
      - 1883:1883
    networks:
      network:
        ipv4_address: 10.5.0.3
  redis:
    image: redis:latest
    container_name: redis 
    ports:
      - 6379:6379
    networks:
      network:
        ipv4_address: 10.5.0.4

volumes:
  mongodb_data_container:

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
