version: '3.7'
services:
  openusp-db:
    image: mongo:latest
    container_name: openusp-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      openusp:
        ipv4_address: 10.5.0.2
  openusp-broker:
    image: rmohr/activemq:latest
    container_name: openusp-broker
    ports:
      - 61616:61616
      - 8161:8161
      - 1883:1883
    networks:
      openusp:
        ipv4_address: 10.5.0.3
  openusp-cache:
    image: redis:latest
    container_name: openusp-cache
    ports:
      - 6379:6379
    networks:
      openusp:
        ipv4_address: 10.5.0.4

volumes:
  mongodb_data_container:

networks:
  openusp:
    name: openusp
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
